/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{156:function(Da,wa,w){function qa(Ja,Ca,Oa,Ma){return Object(fa.b)(void 0,void 0,void 0,function(){var Ba,Ha,Ga,va;return Object(fa.d)(this,function(Fa){switch(Fa.label){case 0:return Ba=Ka.getDocument(),Ha=[1],[4,Object(ia.c)(Ca,{extension:"pdf"})];case 1:return Ga=Fa.da(),va=!0,[4,Ba.pg(Ga,Ha,Ja,va)];case 2:return Fa.da(),[4,Ba.gh([Ja+1],va)];case 3:return Fa.da(),Ka.getDocument().aJ(),Ka.$I(Ja),Ka.xe(),ha(Ja),e(Ja,Oa.galleys,
Ma),e(Ja,Oa.objects,Ma),[2]}})})}function ka(Ja){Ja=(new DOMParser).parseFromString(Ja,"text/html").documentElement.querySelector("body");Ja.querySelectorAll("p").forEach(function(Ca){Ca.querySelectorAll("span").forEach(function(Ba){var Ha=Ba.getAttribute("style");Ha=ja(Ha,Ba.innerHTML);Ba.innerHTML=Ha});var Oa=Ca.getAttribute("style"),Ma=Ca.innerHTML.replaceAll("<br>","");Ca.innerHTML=ja(Oa,Ma)});return Ja.innerHTML.trim()}function ja(Ja,Ca){Ja.includes("bold")&&(Ca="<strong>"+Ca+"</strong>");Ja.includes("italic")&&
(Ca="<em>"+Ca+"</em>");Ja.includes("text-decoration: underline")&&(Ca="<u>"+Ca+"</u>");return Ca}function ha(Ja){var Ca=Ka.pa(),Oa=Ca.Mb().filter(function(Ma){return Ma.Vg()&&Ma.PageNumber===Ja});Ca.kk(Oa,{force:!0,source:"contentEditTool"})}function ea(Ja,Ca){Ca.forEach(function(Oa){xa[Ja]||(xa[Ja]=[]);xa[Ja].find(function(Ma){return Ma.id===Oa.id})||xa[Ja].push(Oa)})}function z(Ja,Ca){Ca.forEach(function(Oa){pa[Ja]||(pa[Ja]=[]);pa[Ja].find(function(Ma){return Ma.id===Oa.id})||pa[Ja].push(Oa)})}
function r(Ja,Ca,Oa,Ma){this.top=Ja;this.left=Ca;this.bottom=Oa;this.right=Ma;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};this.width=function(){return Math.round(this.right-this.left)};this.iO=function(Ba){return this.topVal()!=Ba.topVal()||this.leftVal()!=
Ba.leftVal()||this.bottomVal()!=Ba.bottomVal()||this.rightVal()!=Ba.rightVal()}}function x(Ja,Ca,Oa,Ma,Ba){this.id=Ja;this.pagenum=Ca;this.galleysContents=Oa;this.contents=Ma;this.galleyBox=Ba}function f(Ja,Ca,Oa,Ma){this.id=Ca;this.type=Ja;this.bbox=Oa;this.pagenum=Ma}function a(Ja,Ca,Oa,Ma,Ba){this.id=Ja;this.pagecount=Ca;this.pageBBox=Oa;this.galleys=Ma;this.objects=Ba}function b(Ja,Ca,Oa,Ma,Ba){var Ha=[];(new DOMParser).parseFromString(Ma,"text/html").documentElement.querySelectorAll("p").forEach(function(Pa,
Na){Ha[Na]=Pa.innerHTML});Oa=(new DOMParser).parseFromString(Oa,"text/html");var Ga=null;Oa.documentElement.querySelectorAll("p").forEach(function(Pa,Na){Na<Ha.length?(Pa.innerHTML=Ha[Na],Ga=Pa.getAttribute("style"),Ga=Ga.replace("font:italic","font:normal"),Ga=Ga.replace(" bold "," normal "),Ga=Ga.replace("underline:1;","underline:0;"),Pa.setAttribute("style",Ga)):Pa.remove()});for(Ma=Oa.documentElement.querySelectorAll("p").length;Ma<Ha.length;Ma++){var va=document.createElement("p");va.setAttribute("id",
"0");va.innerHTML=Ha[Ma];null!=Ga&&va.setAttribute("style",Ga);Oa.documentElement.querySelector("body").appendChild(va)}Oa=Oa.documentElement.querySelector("body").innerHTML;var Fa="";pa[Ja].forEach(function(Pa){Pa.id==Ba&&(Fa=Pa)});if(""==Fa)return"";Ca="<DOC id='"+Ca.id+"' pagecount='"+Ca.pagecount+"'>";Ca=Ca+("<STORY galley_ids='"+Ba+"' pagenum='"+Ja+"'><galleys>")+(Fa.galleysContents+"</galleys>");Fa.contents=Oa;Ca=Ca+Oa+"\n</STORY>";return Ca+="</DOC>"}function e(Ja,Ca,Oa){var Ma=[],Ba=Ka.getDocument(),
Ha=null;Ca.forEach(function(Ga){if(Ga instanceof f){var va=Ba.vm(Ja,Ga.bbox.leftVal(),Ga.bbox.topVal());var Fa=va.x;var Pa=va.y;var Na=Ba.vm(Ja,Ga.bbox.rightVal(),Ga.bbox.bottomVal());va=Na.x;Na=Na.y}else if(Ga instanceof x)va=Ba.vm(Ja,Ga.galleyBox.leftVal(),Ga.galleyBox.topVal()),Fa=va.x,Pa=va.y,Na=Ba.vm(Ja,Ga.galleyBox.rightVal(),Ga.galleyBox.bottomVal()),va=Na.x,Na=Na.y;else return;var Ta=new window.Core.Annotations.RectangleAnnotation,Wa=la.a.OBJECT;Ga instanceof x&&(Wa=la.a.TEXT);Ta.qda(Ga,Wa);
Ta.PageNumber=Ga.pagenum;Ta.X=Fa;Ta.Y=Pa;Ta.Width=va-Fa;Ta.Height=Na-Pa;Ta.StrokeColor=new ca.a("#3183C8");Ta.FillColor=new ca.a(255,255,255,.01);Ta.Style="dash";Ta.Dashes="4,3";Ta.BF();Ta.selectionModel=na.a;Ma.push(Ta);"undefined"!==typeof Oa&&Oa===Ga.id&&(Ha=Ta)});Ca=Ka.pa();Ca.Ch(Ma);Ha&&Ca.mh(Ha);Ca.cf(Ma)}function h(Ja,Ca,Oa){return Object(fa.b)(this,void 0,void 0,function(){var Ma,Ba,Ha,Ga,va;return Object(fa.d)(this,function(Fa){switch(Fa.label){case 0:Ma=Ja.data;Ha=Ma.cmd;switch(Ha){case "isReady":return[3,
1];case "initialiseInfixServer":return[3,3];case "exportFile":return[3,4];case "importText":return[3,5];case "transformObject":return[3,5];case "deleteObject":return[3,6]}return[3,7];case 1:return[4,Object(oa.b)()];case 2:return Ga=Fa.da(),ra.postMessage({cmd:"initialiseInfixServer",l:Ga}),[3,7];case 3:return(va=n(Ma.resultsXML))?Ca():Oa("License key does not have content edit permission"),[3,7];case 4:return Ma.exportPerformed?aa(Ma.pageNumber,Ma.exportXML,Ma.objectXML,Ma.resultsXML):(Ba=Ea[Ma.pageNumber],
z(Ma.pageNumber,Ba.galleys),ea(Ma.pageNumber,Ba.objects),ha(Ma.pageNumber),e(Ma.pageNumber,Ba.galleys),e(Ma.pageNumber,Ba.objects)),[3,7];case 5:return Ba=Ea[Ma.pageNumber],da(Ma.pageNumber,Ma.resultsXML),qa(Ma.pageNumber,Ma.pdfBuffer,Ba,Ma.id),[3,7];case 6:return Ba=Ea[Ma.pageNumber],da(Ma.pageNumber,Ma.resultsXML),Ba.galleys=Ba.galleys.filter(function(Pa){return Pa.id!==Ma.id}),Ba.objects=Ba.objects.filter(function(Pa){return Pa.id!==Ma.id}),qa(Ma.pageNumber,Ma.pdfBuffer,Ba),[3,7];case 7:return[2]}})})}
function n(Ja){Ja=new Uint8Array(Ja);var Ca=(new TextDecoder("utf-8")).decode(Ja);Ja=!1;Ca=(new DOMParser).parseFromString(Ca,"text/xml").getElementsByTagName("LicenseCheck");null!==Ca&&0<Ca.length&&(Ca=Ca[0].getElementsByTagName("Status")[0].innerHTML,"error"!=Ca&&"ok"==Ca&&(Ja=!0));return Ja}function aa(Ja,Ca,Oa,Ma){var Ba=new Uint8Array(Ca),Ha=new TextDecoder("utf-8");Ca=Ha.decode(Ba);Ba=new Uint8Array(Oa);Oa=Ha.decode(Ba);Ba=new Uint8Array(Ma);Ma=Ha.decode(Ba);Ea[Ja]=ba(Ja,Ca,Oa,Ma);Ma=Ea[Ja];
z(Ja,Ma.galleys);ea(Ja,Ma.objects);ha(Ja);e(Ja,Ma.galleys);e(Ja,Ma.objects)}function y(Ja,Ca){Ja=parseFloat(Ja);return isNaN(Ca)||Ca<Ja?Ja:Ca}function ba(Ja,Ca,Oa,Ma){var Ba;var Ha=new DOMParser;Ma=Ha.parseFromString(Ma,"text/xml");Array.prototype.slice.call(Ma.getElementsByTagName("BBox")).forEach(function(Fa){if("CropBox"==Fa.getAttribute("Name")){var Pa=parseFloat(Fa.getElementsByTagName("Top").item(0).innerHTML),Na=parseFloat(Fa.getElementsByTagName("Bottom").item(0).innerHTML),Ta=parseFloat(Fa.getElementsByTagName("Left").item(0).innerHTML);
Fa=parseFloat(Fa.getElementsByTagName("Right").item(0).innerHTML);Ba=new r(Pa,Ta,Na,Fa)}});Ha=new DOMParser;Ma=Ha.parseFromString(Ca,"text/xml");var Ga=[];Array.prototype.slice.call(Ma.getElementsByTagName("STORY")).forEach(function(Fa){var Pa=Fa.getAttribute("galley_ids"),Na=Array.prototype.slice.call(Fa.getElementsByTagName("g"))[0],Ta=Na.getAttribute("bbox").split(" ");Ta=new r(parseFloat(Ta[0]),parseFloat(Ta[1]),parseFloat(Ta[2]),parseFloat(Ta[3]));Na=Na.innerHTML;var Wa=Array.prototype.slice.call(Fa.getElementsByTagName("galleys"))[0];
Wa.parentNode.removeChild(Wa);Fa=Fa.innerHTML;Fa=(new DOMParser).parseFromString(Fa,"text/html").documentElement.querySelector("body").innerHTML.trim();Pa=new x(Pa,Ja,Na,Fa,Ta);Ga.push(Pa)});Ha=new DOMParser;var va=[];Ca=Ha.parseFromString(Oa,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(Ca).forEach(function(Fa){var Pa=Fa.getAttribute("Type"),Na=Fa.getAttribute("OID");Fa=Array.prototype.slice.call(Fa.getElementsByTagName("Point"));var Ta=Number.NaN,Wa=Number.NaN,$a=Number.NaN,
db=Number.NaN;Fa.forEach(function(gb){var kb=gb.getAttribute("Name");"TL"==kb?(Ta=y(gb.getAttribute("Y"),Ta),$a=y(gb.getAttribute("X"),$a)):"TR"==kb?(Ta=y(gb.getAttribute("Y"),Ta),db=y(gb.getAttribute("X"),db)):"BR"==kb?(Wa=y(gb.getAttribute("Y"),Wa),db=y(gb.getAttribute("X"),db)):"BL"==kb&&(Wa=y(gb.getAttribute("Y"),Wa),$a=y(gb.getAttribute("X"),$a))});Fa=new r(Ta,$a,Wa,db);Pa=new f(Pa,Na,Fa,Ja);va.push(Pa)});Ca=Array.prototype.slice.call(Ma.getElementsByTagName("DOC"))[0].getAttribute("id");return new a(Ca,
1,Ba,Ga,va)}function da(Ja,Ca){var Oa;Ca=(new TextDecoder("utf-8")).decode(Ca);Ca=(new DOMParser).parseFromString(Ca,"text/xml");var Ma=Ca.getElementsByTagName("Galley").item(0);if(null!=Ma){var Ba=Ma.getAttribute("id");Ma=Ca.getElementsByTagName("BBox");Ma=Array.prototype.slice.call(Ma);Ma.forEach(function(Ga){var va=Ga.getElementsByTagName("Top"),Fa=parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Left");var Pa=parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Bottom");var Na=
parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Right");Ga=parseFloat(va.item(0).innerHTML);Oa=new r(Fa,Pa,Na,Ga)});pa[Ja].forEach(function(Ga){Ga.id==Ba&&1==Oa.iO(Ga.galleyBox)&&(Ga.galleyBox=Oa)})}Ma=Ca.getElementsByTagName("Object").item(0);if(null!=Ma){var Ha=Ma.getAttribute("OID");Ma=Ca.getElementsByTagName("BBox");Ma=Array.prototype.slice.call(Ma);Ma.forEach(function(Ga){var va=Ga.getElementsByTagName("Top"),Fa=parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Left");
var Pa=parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Bottom");var Na=parseFloat(va.item(0).innerHTML);va=Ga.getElementsByTagName("Right");Ga=parseFloat(va.item(0).innerHTML);Oa=new r(Fa,Pa,Na,Ga)});xa[Ja].forEach(function(Ga){Ga.id==Ha&&1==Oa.iO(Ga.bbox)&&(Ga.bbox=Oa)})}}w.r(wa);var fa=w(1),ia=w(63),ca=w(8),na=w(424),ma=w(34),oa=w(73),ta=w(2),la=w(168),ra=null,ua=null,pa={},xa={},Ea={},Ka;wa["default"]={Paa:function(Ja){return Object(fa.b)(void 0,void 0,void 0,function(){return Object(fa.d)(this,
function(){ua||(Ka=Ja,ua=new Promise(function(Ca,Oa){ra=new Worker(window.Core.getWorkerPath()+"contentEdit/InfixServerModule.js");ra.onmessage=function(Ma){h(Ma,Ca,Oa)};ra.postMessage({cmd:"isReady"})}));return[2,ua]})})},Raa:function(Ja,Ca,Oa){return Object(fa.b)(void 0,void 0,void 0,function(){var Ma,Ba,Ha,Ga;return Object(fa.d)(this,function(va){switch(va.label){case 0:return ha(Ca),pa[Ca]=[],xa[Ca]=[],[4,Ja.Bf([Ca])];case 1:return Ma=va.da(),Ba=new TextEncoder,Ha=Ba.encode(""),Ga=Ha.buffer,ra.postMessage({cmd:"exportFile",
pageNumber:Ca,performExport:Oa,pdfFile:Ma,tableData:Ga},[Ma,Ga]),[2]}})})},w2:function(Ja){return Object(fa.b)(void 0,void 0,void 0,function(){var Ca,Oa,Ma,Ba,Ha,Ga,va,Fa;return Object(fa.d)(this,function(Pa){switch(Pa.label){case 0:return Ca=Ja.id,Oa=Ja.isText,Ma=Ja.pageNumber,Ba=Ka.getDocument(),[4,Ba.Bf([Ma])];case 1:return Ha=Pa.da(),Ga=new TextEncoder,va=Ga.encode(""),Fa=va.buffer,ra.postMessage({cmd:"deleteObject",pdfFile:Ha,pageNumber:Ma,objectID:Ca,isText:Oa,tableData:Fa},[Fa]),[2]}})})},
Lfa:function(Ja){return Object(fa.b)(void 0,void 0,void 0,function(){var Ca,Oa,Ma,Ba,Ha,Ga,va,Fa,Pa,Na,Ta,Wa,$a;return Object(fa.d)(this,function(db){switch(db.label){case 0:return Ca=Ja.id,Oa=Ja.position,Ma=Oa.top,Ba=Oa.left,Ha=Oa.bottom,Ga=Oa.right,va=Ja.isText,Fa=Ja.pageNumber,Pa=Ka.getDocument(),[4,Pa.Bf([Fa])];case 1:return Na=db.da(),Ta=new TextEncoder,Wa=Ta.encode(""),$a=Wa.buffer,ra.postMessage({cmd:"transformObject",pdfFile:Na,pageNumber:Fa,objectID:Ca,isText:va,topVal:Ma,leftVal:Ba,bottomVal:Ha,
rightVal:Ga,tableData:$a},[$a]),[2]}})})},cga:function(Ja,Ca){return Object(fa.b)(void 0,void 0,void 0,function(){var Oa,Ma,Ba,Ha,Ga,va,Fa,Pa,Na,Ta,Wa,$a,db,gb,kb;return Object(fa.d)(this,function(lb){switch(lb.label){case 0:Oa=Ca.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");Ma=Ja.Us.id;Ba=Ja.PageNumber;Ha=Ea[Ba];Ga=Ha.galleys.find(function(ib){return ib.id===Ma});va=ka(Ga.contents);Fa=b(Ba,Ha,va,Oa,Ma);if(""==Fa)return[3,2];Pa=new TextEncoder;Na=Pa.encode(Fa);Ta=Na.buffer;
Wa=Object(ma.c)()||"https://www.pdftron.com/webfonts/v2/";$a=Ka.getDocument();return[4,$a.Bf([Ba])];case 1:return db=lb.da(),Pa=new TextEncoder,gb=Pa.encode(""),kb=gb.buffer,ra.postMessage({cmd:"importText",pdfFile:db,pageNumber:Ba,webFontURL:Wa,galleyId:Ma,importData:Ta,tableData:kb},[Ta,kb]),[3,3];case 2:Object(ta.f)("Unable to generate import XML"),lb.label=3;case 3:return[2]}})})},u6:function(Ja){if(Ja)return ka(Ja.contents);Object(ta.f)("Unable to extract document content")}}},424:function(Da,
wa,w){var qa=w(1);Da=w(78);var ka=w(44);w=function(ja){function ha(){return null!==ja&&ja.apply(this,arguments)||this}Object(qa.c)(ha,ja);ha.prototype.testSelection=function(ea,z,r){return ka.a.ck(ea,z,r)};return ha}(Da.a);wa.a=w}}]);}).call(this || window)
