/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{384:function(Da,wa,w){w.r(wa);w.d(wa,"ByteRangeRequest",function(){return aa});var qa=w(1),ka=w(0);w.n(ka);var ja=w(2),ha=w(137);Da=w(88);var ea=w(233),z=w(68),r=w(64),x=w(232),f=w(155);w=w(352);var a=[],b=[],e=window,h=function(){return function(){this.cl=1}}(),n;(function(ba){ba[ba.UNSENT=0]="UNSENT";ba[ba.DONE=4]="DONE"})(n||(n={}));var aa=function(){function ba(da,fa,ia,ca){var na=this;this.url=da;this.range=fa;this.Je=ia;
this.withCredentials=ca;this.MY=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);e.Uint8Array&&(this.request.responseType="arraybuffer");ca&&(this.request.withCredentials=ca);y.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(fa.stop)?this.request.setRequestHeader("Range","bytes="+fa.start):this.request.setRequestHeader("Range",["bytes=",fa.start,"-",fa.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");ia&&Object.keys(ia).forEach(function(ma){na.request.setRequestHeader(ma,
ia[ma])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=x.a.NOT_STARTED}ba.prototype.start=function(da){var fa=this,ia=this.request;ia.onreadystatechange=function(){if(fa.aborted)return fa.status=x.a.ABORTED,da({code:x.a.ABORTED});if(this.readyState===fa.MY.DONE){fa.yA();var ca=0===window.document.URL.indexOf("file:///");200===ia.status||206===ia.status||ca&&0===ia.status?
(ca=e.wQ(this),fa.iK(ca,da)):(fa.status=x.a.ERROR,da({code:fa.status,status:fa.status}))}};this.request.send(null);this.status=x.a.STARTED};ba.prototype.iK=function(da,fa){this.status=x.a.SUCCESS;if(fa)return fa(!1,da)};ba.prototype.abort=function(){this.yA();this.aborted=!0;this.request.abort()};ba.prototype.yA=function(){var da=Object(f.c)(this.url,this.range,b);-1!==da&&b.splice(da,1);if(0<a.length){da=a.shift();var fa=new ba(da.url,da.range,this.Je,this.withCredentials);da.request=fa;b.push(da);
fa.start(Object(f.d)(da))}};ba.prototype.extend=function(da){var fa=Object.assign({},this,da.prototype);fa.constructor=da;return fa};return ba}(),y=function(ba){function da(fa,ia,ca,na,ma){ca=ba.call(this,fa,ca,na)||this;ca.fl={};ca.$y=ia;ca.url=fa;ca.DISABLE_RANGE_HEADER=!1;ca.Sv=aa;ca.ZK=3;ca.Je=ma||{};return ca}Object(qa.c)(da,ba);da.prototype.au=function(fa,ia,ca){var na=-1===fa.indexOf("?")?"?":"&";switch(ca){case !1:case r.a.NEVER_CACHE:fa=fa+na+"_="+Object(ka.uniqueId)();break;case !0:case r.a.CACHE:fa=
fa+na+"_="+ia.start+","+(Object(ka.isUndefined)(ia.stop)?"":ia.stop)}return fa};da.prototype.NO=function(fa,ia,ca,na){void 0===ca&&(ca={});return new this.Sv(fa,ia,ca,na)};da.prototype.b5=function(fa,ia,ca,na,ma){for(var oa=0;oa<a.length;oa++)if(Object(ka.isEqual)(a[oa].range,ia)&&Object(ka.isEqual)(a[oa].url,fa))return a[oa].bg.push(na),a[oa].yB++,null;for(oa=0;oa<b.length;oa++)if(Object(ka.isEqual)(b[oa].range,ia)&&Object(ka.isEqual)(b[oa].url,fa))return b[oa].bg.push(na),b[oa].yB++,null;ca={url:fa,
range:ia,$y:ca,bg:[na],yB:1};if(0===a.length&&b.length<this.ZK)return b.push(ca),ca.request=this.NO(fa,ia,ma,this.withCredentials),ca;a.push(ca);return null};da.prototype.Em=function(fa,ia,ca){var na=this.au(fa,ia,this.$y);(fa=this.b5(na,ia,this.$y,ca,this.Je))&&fa.request.start(Object(f.d)(fa));return function(){var ma=Object(f.c)(na,ia,b);if(-1!==ma){var oa=--b[ma].yB;0===oa&&b[ma].request&&b[ma].request.abort()}else ma=Object(f.c)(na,ia,a),-1!==ma&&(oa=--a[ma].yB,0===oa&&a.splice(ma,1))}};da.prototype.cQ=
function(){return{start:-ha.a}};da.prototype.b8=function(){var fa=-(ha.a+ha.e);return{start:fa-ha.d,end:fa}};da.prototype.Ar=function(fa){var ia=this;this.fz=!0;var ca=ha.a;this.Em(this.url,this.cQ(),function(na,ma,oa){function ta(){var la=ia.zd.ZP();ia.Em(ia.url,la,function(ra,ua){if(ra)return Object(ja.i)("Error loading central directory: "+ra),fa(ra);ua=Object(z.a)(ua);if(ua.length!==la.stop-la.start)return fa("Invalid XOD file: Zip central directory data is wrong size! Should be "+(la.stop-la.start)+
" but is "+ua.length);ia.zd.vT(ua);ia.eF=!0;ia.fz=!1;return fa(!1)})}if(na)return Object(ja.i)("Error loading end header: "+na),fa(na,ma,oa);ma=Object(z.a)(ma);if(ma.length!==ca)return fa("Invalid XOD file: Zip end header data is wrong size!");try{ia.zd=new ea.a(ma)}catch(la){return fa(la)}ia.zd.C9?ia.Em(ia.url,ia.b8(),function(la,ra){if(la)return Object(ja.i)("Error loading zip64 header: "+la),fa(la);ra=Object(z.a)(ra);ia.zd.U9(ra);ta()}):ta()})};da.prototype.tQ=function(fa){fa(Object.keys(this.zd.fm))};
da.prototype.VI=function(fa,ia){var ca=this;if(this.zd.GO(fa)){var na=this.zd.pA(fa);if(na in this.fl){var ma=this.ih[fa];ma.xq=this.fl[na];ma.xq.cl++;ma.cancel=ma.xq.cancel}else{var oa=this.zd.A6(fa),ta=this.Em(this.url,oa,function(ra,ua){ra?(Object(ja.i)('Error loading part "'+fa+'": '+ra),ca.Em(ca.url,oa,function(pa,xa){if(pa)return ia(pa,fa);ca.zT(xa,oa,na,fa,ia)})):ca.zT(ua,oa,na,fa,ia)}),la=this.ih[fa];la&&(la.AV=!0,la.cancel=function(){la.xq.cl--;0===la.xq.cl&&(ta(),delete ca.fl[na])},this.fl[na]=
new h(na),la.xq=this.fl[na],la.xq.cancel=la.cancel)}}else delete this.ih[fa],ia(Error('File not found: "'+fa+'"'),fa)};da.prototype.zT=function(fa,ia,ca,na,ma){if(fa.length!==ia.stop-ia.start)ma(Error("Part data is wrong size!"),na);else{do{if(!this.fl[ca])return;na=this.fl[ca].cl;for(var oa=ia.mp.length,ta=0;ta<oa;++ta){var la=ia.mp[ta];ma(!1,la.hp,fa["string"===typeof fa?"substring":"subarray"](la.start,la.stop),this.zd.pR(la.hp));la.hp in this.ih&&delete this.ih[la.hp]}}while(na!==this.fl[ca].cl);
delete this.fl[ca]}};da.DISABLE_RANGE_HEADER=!1;da.ZK=3;return da}(Da.a);(function(ba){function da(fa,ia,ca){var na=ba.call(this)||this,ma;for(ma in fa)na[ma]=fa[ma];na.zja=fa;na.startOffset=ia;na.endOffset=ca;na.NO=function(oa,ta,la,ra){Object(ka.isUndefined)(ta.stop)?(ta.start+=na.endOffset,ta.stop=na.endOffset):(ta.start+=na.startOffset,ta.stop+=na.startOffset);oa=na.au(na.url,ta,na.$y);return new fa.Sv(oa,ta,la,ra)};return na}Object(qa.c)(da,ba);return da})(y);Object(w.a)(y);Object(w.b)(y);wa["default"]=
y}}]);}).call(this || window)
