/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{393:function(Da,wa,w){w.r(wa);var qa=w(1),ka=w(0);w.n(ka);var ja=w(2),ha=w(137);Da=w(49);var ea=w(88),z=w(233),r=w(64),x=w(232);w=w(352);var f=window,a=function(){function h(n,aa,y){var ba=-1===n.indexOf("?")?"?":"&";switch(aa){case r.a.NEVER_CACHE:this.url=n+ba+"_="+Object(ka.uniqueId)();break;default:this.url=n}this.Je=y;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=x.a.NOT_STARTED}h.prototype.start=function(n,aa){var y=this,ba=this,da=this.request,fa;ba.jv=0;n&&Object.keys(n).forEach(function(ia){y.request.setRequestHeader(ia,n[ia])});aa&&(this.request.withCredentials=aa);this.VB=setInterval(function(){var ia=0===window.document.URL.indexOf("file:///");ia=200===da.status||
ia&&0===da.status;if(da.readyState!==x.b.DONE||ia){try{da.responseText}catch(ca){return}ba.jv<da.responseText.length&&(fa=ba.eba())&&ba.trigger(h.Events.DATA,[fa]);0===da.readyState&&(clearInterval(ba.VB),ba.trigger(h.Events.DONE))}else clearInterval(ba.VB),ba.trigger(h.Events.DONE,["Error received return status "+da.status])},1E3);this.request.send(null);this.status=x.a.STARTED};h.prototype.eba=function(){var n=this.request,aa=n.responseText;if(0!==aa.length)if(this.jv===aa.length)clearInterval(this.VB),
this.trigger(h.Events.DONE);else return aa=Math.min(this.jv+3E6,aa.length),n=f.wQ(n,this.jv,!0,aa),this.jv=aa,n};h.prototype.abort=function(){clearInterval(this.VB);var n=this;this.request.onreadystatechange=function(){Object(ja.i)("StreamingRequest aborted");n.status=x.a.ABORTED;return n.trigger(h.Events.ABORTED)};this.request.abort()};h.prototype.finish=function(){var n=this;this.request.onreadystatechange=function(){n.status=x.a.SUCCESS;return n.trigger(h.Events.DONE)};this.request.abort()};h.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return h}();Object(Da.a)(a);var b;(function(h){h[h.LOCAL_HEADER=0]="LOCAL_HEADER";h[h.FILE=1]="FILE";h[h.CENTRAL_DIR=2]="CENTRAL_DIR"})(b||(b={}));var e=function(h){function n(){var aa=h.call(this)||this;aa.buffer="";aa.state=b.LOCAL_HEADER;aa.bK=4;aa.Rk=null;aa.Er=ha.c;aa.fm={};return aa}Object(qa.c)(n,h);n.prototype.Zaa=function(aa){var y;for(aa=this.buffer+aa;aa.length>=this.Er;)switch(this.state){case b.LOCAL_HEADER:this.Rk=y=this.iba(aa.slice(0,this.Er));
if(y.es!==ha.g)throw Error("Wrong signature in local header: "+y.es);aa=aa.slice(this.Er);this.state=b.FILE;this.Er=y.WE+y.Yo+y.pu+this.bK;this.trigger(n.Events.HEADER,[y]);break;case b.FILE:this.Rk.name=aa.slice(0,this.Rk.Yo);this.fm[this.Rk.name]=this.Rk;y=this.Er-this.bK;var ba=aa.slice(this.Rk.Yo+this.Rk.pu,y);this.trigger(n.Events.FILE,[this.Rk.name,ba,this.Rk.mF]);aa=aa.slice(y);if(aa.slice(0,this.bK)===ha.h)this.state=b.LOCAL_HEADER,this.Er=ha.c;else return this.state=b.CENTRAL_DIR,!0}this.buffer=
aa;return!1};n.Events={HEADER:"header",FILE:"file"};return n}(z.a);Object(Da.a)(e);Da=function(h){function n(aa,y,ba,da,fa){ba=h.call(this,aa,ba,da)||this;ba.url=aa;ba.stream=new a(aa,y);ba.zd=new e;ba.fT=window.createPromiseCapability();ba.GT={};ba.Je=fa;return ba}Object(qa.c)(n,h);n.prototype.$v=function(aa){var y=this;this.request([this.ti,this.Kj,this.si]);this.stream.addEventListener(a.Events.DATA,function(ba){try{if(y.zd.Zaa(ba))return y.stream.finish()}catch(da){throw y.stream.abort(),y.mu(da),
aa(da),da;}});this.stream.addEventListener(a.Events.DONE,function(ba){y.Eaa=!0;y.fT.resolve();ba&&(y.mu(ba),aa(ba))});this.zd.addEventListener(e.Events.HEADER,Object(ka.bind)(this.ET,this));this.zd.addEventListener(e.Events.FILE,Object(ka.bind)(this.yba,this));return this.stream.start(this.Je,this.withCredentials)};n.prototype.tQ=function(aa){var y=this;this.fT.promise.then(function(){aa(Object.keys(y.zd.fm))})};n.prototype.Mm=function(){return!0};n.prototype.request=function(aa){var y=this;this.Eaa&&
aa.forEach(function(ba){y.GT[ba]||y.Nfa(ba)})};n.prototype.ET=function(){};n.prototype.abort=function(){this.stream&&this.stream.abort()};n.prototype.Nfa=function(aa){this.trigger(ea.a.Events.PART_READY,[{Wa:aa,error:"Requested part not found",Hh:!1,zf:!1}])};n.prototype.yba=function(aa,y,ba){this.GT[aa]=!0;this.trigger(ea.a.Events.PART_READY,[{Wa:aa,data:y,Hh:!1,zf:!1,error:null,Kc:ba}])};return n}(ea.a);Object(w.a)(Da);Object(w.b)(Da);wa["default"]=Da}}]);}).call(this || window)
