/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{399:function(Da,wa,w){w.r(wa);var qa=w(1),ka=w(425),ja=w(426),ha;(function(ea){ea[ea.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ea[ea.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ea[ea.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ha||(ha={}));Da=function(){function ea(z){this.V=z;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED}ea.prototype.S7=function(){var z=this;return function(r,x,f){return Object(qa.b)(z,
void 0,void 0,function(){var a,b,e,h,n,aa,y,ba=this,da;return Object(qa.d)(this,function(fa){switch(fa.label){case 0:if(this.state!==ha.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];a=this.V.getDocument().Rq();return[4,this.y6(a)];case 1:b=fa.da(),e=this.U1(b),this.XF=null!==(da=null===e||void 0===e?void 0:e.parse())&&void 0!==da?da:null,this.state=null===this.XF?ha.EXTERNAL_XFDF_NOT_AVAILABLE:ha.EXTERNAL_XFDF_AVAILABLE,fa.label=2;case 2:if(this.state===ha.EXTERNAL_XFDF_NOT_AVAILABLE)return f(r),[2];h=
new DOMParser;n=h.parseFromString(r,"text/xml");x.forEach(function(ia){ba.merge(n,ba.XF,ia-1)});aa=new XMLSerializer;y=aa.serializeToString(n);f(y);return[2]}})})}};ea.prototype.DJ=function(z){this.y6=z};ea.prototype.Rd=function(){this.XF=void 0;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED};ea.prototype.U1=function(z){return z?Array.isArray(z)?new ka.a(z):"string"!==typeof z?null:(new DOMParser).parseFromString(z,"text/xml").querySelector("xfdf > add")?new ka.a(z):new ja.a(z):null};ea.prototype.merge=
function(z,r,x){var f=this;0===x&&(this.g$(z,r.Pn),this.i$(z,r.EF));var a=r.ba[x];a&&(this.j$(z,a.Sl),this.l$(z,a.oW,r.qu),this.k$(z,a.page,x),this.h$(z,a.WO));a=this.V.vc();if(x===a-1){var b=r.qu;Object.keys(b).forEach(function(e){b[e].gH||f.iS(z,e,b[e])})}};ea.prototype.g$=function(z,r){null!==r&&(z=this.Jt(z),this.lp(z,"calculation-order",r))};ea.prototype.i$=function(z,r){null!==r&&(z=this.Jt(z),this.lp(z,"document-actions",r))};ea.prototype.j$=function(z,r){var x=this,f=this.It(z.querySelector("xfdf"),
"annots");Object.keys(r).forEach(function(a){x.lp(f,'[name="'+a+'"]',r[a])})};ea.prototype.l$=function(z,r,x){var f=this;if(0!==r.length){var a=this.Jt(z);r.forEach(function(b){var e=b.getAttribute("field"),h=x[e];h&&(f.iS(z,e,h),f.lp(a,"null",b))})}};ea.prototype.iS=function(z,r,x){var f=this.Jt(z);null!==x.Wz&&this.lp(f,'ffield [name="'+r+'"]',x.Wz);z=this.It(z.querySelector("xfdf"),"fields");r=r.split(".");this.SI(z,r,0,x.value);x.gH=!0};ea.prototype.k$=function(z,r,x){null!==r&&(z=this.Jt(z),
z=this.It(z,"pages"),this.lp(z,'[number="'+(x+1)+'"]',r))};ea.prototype.h$=function(z,r){Object.keys(r).forEach(function(x){(x=z.querySelector('annots [name="'+x+'"]'))&&x.parentElement.removeChild(x)})};ea.prototype.SI=function(z,r,x,f){if(x===r.length)r=document.createElementNS("","value"),r.textContent=f,this.lp(z,"value",r);else{var a=r[x];this.It(z,'[name="'+a+'"]',"field").setAttribute("name",a);z=z.querySelectorAll('[name="'+a+'"]');1===z.length?this.SI(z[0],r,x+1,f):(a=this.w5(z),this.SI(x===
r.length-1?a:this.Bfa(z,a),r,x+1,f))}};ea.prototype.w5=function(z){for(var r=null,x=0;x<z.length;x++){var f=z[x];if(0===f.childElementCount||1===f.childElementCount&&"value"===f.children[0].tagName){r=f;break}}return r};ea.prototype.Bfa=function(z,r){for(var x=0;x<z.length;x++)if(z[x]!==r)return z[x];return null};ea.prototype.lp=function(z,r,x){r=z.querySelector(r);null!==r&&z.removeChild(r);z.appendChild(x)};ea.prototype.Jt=function(z){var r=z.querySelector("pdf-info");if(null!==r)return r;r=this.It(z.querySelector("xfdf"),
"pdf-info");r.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");r.setAttribute("version","2");r.setAttribute("import-version","4");return r};ea.prototype.It=function(z,r,x){var f=z.querySelector(r);if(null!==f)return f;f=document.createElementNS("",x||r);z.appendChild(f);return f};return ea}();wa["default"]=Da},410:function(Da,wa){Da=function(){function w(){}w.prototype.Dy=function(qa){var ka={Pn:null,EF:null,qu:{},ba:{}};qa=(new DOMParser).parseFromString(qa,"text/xml");ka.Pn=qa.querySelector("pdf-info calculation-order");
ka.EF=qa.querySelector("pdf-info document-actions");ka.qu=this.aaa(qa);ka.ba=this.maa(qa);return ka};w.prototype.aaa=function(qa){var ka=qa.querySelector("fields");qa=qa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===qa)return{};var ja={};this.J_(ja,ka);this.H_(ja,qa);return ja};w.prototype.J_=function(qa,ka){if(null!==ka&&ka.children){for(var ja=[],ha=0;ha<ka.children.length;ha++){var ea=ka.children[ha];ja.push({name:ea.getAttribute("name"),element:ea})}for(;0!==ja.length;)for(ka=ja.shift(),
ha=0;ha<ka.element.children.length;ha++)ea=ka.element.children[ha],"value"===ea.tagName?qa[ka.name]={value:ea.textContent,Wz:null,gH:!1}:ea.children&&ja.push({name:ka.name+"."+ea.getAttribute("name"),element:ea})}};w.prototype.H_=function(qa,ka){ka.forEach(function(ja){var ha=ja.getAttribute("name");qa[ha]?qa[ha].Wz=ja:qa[ha]={value:null,Wz:ja,gH:!1}})};w.prototype.maa=function(qa){var ka=this,ja={};qa.querySelectorAll("pdf-info widget").forEach(function(ha){var ea=parseInt(ha.getAttribute("page"),
10)-1;ka.WA(ja,ea);ja[ea].oW.push(ha)});qa.querySelectorAll("pdf-info page").forEach(function(ha){var ea=parseInt(ha.getAttribute("number"),10)-1;ka.WA(ja,ea);ja[ea].page=ha});this.lQ(qa).forEach(function(ha){var ea=parseInt(ha.getAttribute("page"),10),z=ha.getAttribute("name");ka.WA(ja,ea);ja[ea].Sl[z]=ha});this.YP(qa).forEach(function(ha){var ea=parseInt(ha.getAttribute("page"),10);ha=ha.textContent;ka.WA(ja,ea);ja[ea].WO[ha]=!0});return ja};w.prototype.WA=function(qa,ka){qa[ka]||(qa[ka]={Sl:{},
WO:{},oW:[],page:null})};return w}();wa.a=Da},425:function(Da,wa,w){var qa=w(1),ka=w(0);w.n(ka);Da=function(ja){function ha(ea){var z=ja.call(this)||this;z.k5=Array.isArray(ea)?ea:[ea];return z}Object(qa.c)(ha,ja);ha.prototype.parse=function(){var ea=this,z={Pn:null,EF:null,qu:{},ba:{}};this.k5.forEach(function(r){z=Object(ka.merge)(z,ea.Dy(r))});return z};ha.prototype.lQ=function(ea){var z=[];ea.querySelectorAll("add > *").forEach(function(r){z.push(r)});ea.querySelectorAll("modify > *").forEach(function(r){z.push(r)});
return z};ha.prototype.YP=function(ea){return ea.querySelectorAll("delete > *")};return ha}(w(410).a);wa.a=Da},426:function(Da,wa,w){var qa=w(1);Da=function(ka){function ja(ha){var ea=ka.call(this)||this;ea.l5=ha;return ea}Object(qa.c)(ja,ka);ja.prototype.parse=function(){return this.Dy(this.l5)};ja.prototype.lQ=function(ha){return ha.querySelectorAll("annots > *")};ja.prototype.YP=function(){return[]};return ja}(w(410).a);wa.a=Da}}]);}).call(this || window)
