/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{398:function(Da,wa,w){function qa(ia){ia.Ea();ia.advance();var ca=ia.current.textContent;ia.Ta();return ca}function ka(ia){var ca=[];for(ia.Ea();ia.advance();){var na=ia.Ha();"field"===na?ca.push(String(ia.ea("name"))):Object(e.i)("unrecognised field list element: "+na)}ia.Ta();return ca}function ja(ia,ca){return ca?"false"!==ia:"true"===ia}function ha(ia,ca){var na=ia.Ha();switch(na){case "javascript":return{name:"JavaScript",
javascript:ia.current.textContent};case "uri":return{name:"URI",uri:ia.ea("uri")};case "goto":na=null;ia.Ea();if(ia.advance()){var ma=ia.ea("fit");na={page:ia.ea("page"),fit:ma};if("0"===na.page)Object(e.i)("null page encountered in dest");else switch(ca=ca(Number(na.page)),ma){case "Fit":case "FitB":break;case "FitH":case "FitBH":na.top=ca.la({x:0,y:ia.ea("top")||0}).y;break;case "FitV":case "FitBV":na.left=ca.la({x:ia.ea("left")||0,y:0}).x;break;case "FitR":ma=ca.la({x:ia.ea("left")||0,y:ia.ea("top")||
0});ca=ca.la({x:ia.ea("right")||0,y:ia.ea("bottom")||0});ca=new aa.d(ma.x,ma.y,ca.x,ca.y);na.top=ca.y1;na.left=ca.x1;na.bottom=ca.y2;na.right=ca.x2;break;case "XYZ":ma=ca.la({x:ia.ea("left")||0,y:ia.ea("top")||0});na.top=ma.y;na.left=ma.x;na.zoom=ia.ea("zoom")||0;break;default:Object(e.i)("unknown dest fit: "+ma)}na={name:"GoTo",dest:na}}else Object(e.i)("missing dest in GoTo action");ia.Ta();return na;case "submit-form":na={name:"SubmitForm",url:ia.ea("url"),format:ia.ea("format"),method:ia.ea("method")||
"POST",exclude:ja(ia.ea("exclude"),!1)};ca=ia.ea("flags");na.flags=ca?ca.split(" "):[];for(ia.Ea();ia.advance();)switch(ca=ia.Ha(),ca){case "fields":na.fields=ka(ia);break;default:Object(e.i)("unrecognised submit-form child: "+ca)}ia.Ta();return na;case "reset-form":na={name:"ResetForm",exclude:ja(ia.ea("exclude"),!1)};for(ia.Ea();ia.advance();)switch(ca=ia.Ha(),ca){case "fields":na.fields=ka(ia);break;default:Object(e.i)("unrecognised reset-form child: "+ca)}ia.Ta();return na;case "hide":na={name:"Hide",
hide:ja(ia.ea("hide"),!0)};for(ia.Ea();ia.advance();)switch(ca=ia.Ha(),ca){case "fields":na.fields=ka(ia);break;default:Object(e.i)("unrecognised hide child: "+ca)}ia.Ta();return na;case "named":return{name:"Named",action:ia.ea("name")};default:Object(e.i)("Encountered unexpected action type: "+na)}return null}function ea(ia,ca,na){var ma={};for(ia.Ea();ia.advance();){var oa=ia.Ha();switch(oa){case "action":oa=ia.ea("trigger");if(ca?-1!==ca.indexOf(oa):1){ma[oa]=[];for(ia.Ea();ia.advance();){var ta=
ha(ia,na);Object(h.isNull)(ta)||ma[oa].push(ta)}ia.Ta()}else Object(e.i)("encountered unexpected trigger on field: "+oa);break;default:Object(e.i)("encountered unknown action child: "+oa)}}ia.Ta();return ma}function z(ia){return new y.a(ia.ea("r")||0,ia.ea("g")||0,ia.ea("b")||0,ia.ea("a")||1)}function r(ia,ca){var na=ia.ea("name"),ma=ia.ea("type")||"Type1",oa=ia.ea("size"),ta=ca.la({x:0,y:0});oa=ca.la({x:Number(oa),y:0});ca=ta.x-oa.x;ta=ta.y-oa.y;na={name:na,type:ma,size:Math.sqrt(ca*ca+ta*ta)||0,
strokeColor:[0,0,0],fillColor:[0,0,0]};for(ia.Ea();ia.advance();)switch(ma=ia.Ha(),ma){case "stroke-color":na.strokeColor=z(ia);break;case "fill-color":na.fillColor=z(ia);break;default:Object(e.i)("unrecognised font child: "+ma)}ia.Ta();return na}function x(ia){var ca=[];for(ia.Ea();ia.advance();){var na=ia.Ha();switch(na){case "option":na=ca;var ma=na.push;var oa=ia;oa={value:oa.ea("value"),displayValue:oa.ea("display-value")||void 0};ma.call(na,oa);break;default:Object(e.i)("unrecognised options child: "+
na)}}ia.Ta();return ca}function f(ia,ca){var na=ia.ea("name"),ma={type:ia.ea("type"),quadding:ia.ea("quadding")||"Left-justified",maxLen:ia.ea("max-len")||-1},oa=ia.ea("flags");Object(h.isString)(oa)&&(ma.flags=oa.split(" "));for(ia.Ea();ia.advance();)switch(oa=ia.Ha(),oa){case "actions":ma.actions=ea(ia,["C","F","K","V"],function(){return ca});break;case "default-value":ma.defaultValue=qa(ia);break;case "font":ma.font=r(ia,ca);break;case "options":ma.options=x(ia);break;default:Object(e.i)("unknown field child: "+
oa)}ia.Ta();return new window.Annotations.fa.oa(na,ma)}function a(ia,ca){switch(ia.type){case "Tx":try{if(Object(da.c)(ia.actions))return new n.a.DatePickerWidgetAnnotation(ia,ca)}catch(na){Object(e.i)(na)}return new n.a.TextWidgetAnnotation(ia,ca);case "Ch":return ia.flags.get(fa.WidgetFlags.COMBO)?new n.a.ChoiceWidgetAnnotation(ia,ca):new n.a.ListWidgetAnnotation(ia,ca);case "Btn":return ia.flags.get(fa.WidgetFlags.PUSH_BUTTON)?new n.a.PushButtonWidgetAnnotation(ia,ca):ia.flags.get(fa.WidgetFlags.RADIO)?
new n.a.RadioButtonWidgetAnnotation(ia,ca):new n.a.CheckButtonWidgetAnnotation(ia,ca);case "Sig":return new n.a.SignatureWidgetAnnotation(ia,ca);default:Object(e.i)("Unrecognised field type: "+ia.type)}return null}function b(ia,ca,na,ma){var oa=[],ta={};ia.Ea();var la=[],ra={},ua=[];Object(ba.a)(function(){if(ia.advance()){var pa=ia.Ha();switch(pa){case "calculation-order":la="calculation-order"===ia.Ha()?ka(ia):[];break;case "document-actions":ra=ea(ia,["Init","Open"],ca);break;case "pages":pa=[];
for(ia.Ea();ia.advance();){var xa=ia.Ha();switch(xa){case "page":xa=pa;var Ea=xa.push,Ka=ia,Ja=ca,Ca={number:Ka.ea("number")};for(Ka.Ea();Ka.advance();){var Oa=Ka.Ha();switch(Oa){case "actions":Ca.actions=ea(Ka,["O","C"],Ja);break;default:Object(e.i)("unrecognised page child: "+Oa)}}Ka.Ta();Ea.call(xa,Ca);break;default:Object(e.i)("unrecognised page child: "+xa)}}ia.Ta();ua=pa;break;case "field":xa=f(ia,ca(1));ta[xa.name]=xa;break;case "widget":pa={border:{style:"Solid",width:1},backgroundColor:[],
fieldName:ia.ea("field"),page:ia.ea("page"),index:ia.ea("index")||0,rotation:ia.ea("rotation")||0,flags:[],isImporting:!0};(xa=ia.ea("appearance"))&&(pa.appearance=xa);(xa=ia.ea("flags"))&&(pa.flags=xa.split(" "));for(ia.Ea();ia.advance();)switch(xa=ia.Ha(),xa){case "rect":Ea=ia;Ka=ca(Number(pa.page));xa=Ka.la({x:Ea.ea("x1")||0,y:Ea.ea("y1")||0});Ea=Ka.la({x:Ea.ea("x2")||0,y:Ea.ea("y2")||0});xa=new aa.d(xa.x,xa.y,Ea.x,Ea.y);xa.normalize();pa.rect={x1:xa.x1,y1:xa.y1,x2:xa.x2,y2:xa.y2};break;case "border":xa=
ia;Ea={style:xa.ea("style")||"Solid",width:xa.ea("width")||1,color:[0,0,0]};for(xa.Ea();xa.advance();)switch(Ka=xa.Ha(),Ka){case "color":Ea.color=z(xa);break;default:Object(e.i)("unrecognised border child: "+Ka)}xa.Ta();pa.border=Ea;break;case "background-color":pa.backgroundColor=z(ia);break;case "actions":pa.actions=ea(ia,"E X D U Fo Bl PO PC PV PI".split(" "),ca);break;case "appearances":xa=ia;Ea=Object(da.b)(pa,"appearances");for(xa.Ea();xa.advance();)if(Ka=xa.Ha(),"appearance"===Ka){Ka=xa.ea("name");
Ja=Object(da.b)(Ea,Ka);Ka=xa;for(Ka.Ea();Ka.advance();)switch(Ca=Ka.Ha(),Ca){case "Normal":Object(da.b)(Ja,"Normal").data=Ka.current.textContent;break;default:Object(e.i)("unexpected appearance state: ",Ca)}Ka.Ta()}else Object(e.i)("unexpected appearances child: "+Ka);xa.Ta();break;case "extra":xa=ia;Ea=ca;Ka={};for(xa.Ea();xa.advance();)switch(Ja=xa.Ha(),Ja){case "font":Ka.font=r(xa,Ea(1));break;default:Object(e.i)("unrecognised extra child: "+Ja)}xa.Ta();xa=Ka;xa.font&&(pa.font=xa.font);break;case "captions":Ea=
ia;xa={};(Ka=Ea.ea("Normal"))&&(xa.Normal=Ka);(Ka=Ea.ea("Rollover"))&&(xa.Rollover=Ka);(Ea=Ea.ea("Down"))&&(xa.Down=Ea);pa.captions=xa;break;default:Object(e.i)("unrecognised widget child: "+xa)}ia.Ta();(xa=ta[pa.fieldName])?(pa=a(xa,pa),oa.push(pa)):Object(e.i)("ignoring widget with no corresponding field data: "+pa.fieldName);break;default:Object(e.i)("Unknown element encountered in PDFInfo: "+pa)}return!0}return!1},function(){ia.Ta();na({calculationOrder:la,widgets:oa,fields:ta,documentActions:ra,
pages:ua,custom:[]})},ma)}w.r(wa);w.d(wa,"parse",function(){return b});var e=w(2),h=w(0);w.n(h);var n=w(112),aa=w(3),y=w(8),ba=w(20),da=w(98),fa=w(22)}}]);}).call(this || window)
