/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[1],{404:function(Da,wa,w){(function(qa){function ka(){try{var la=new Uint8Array(1);la.__proto__={__proto__:Uint8Array.prototype,Bia:function(){return 42}};return"function"===typeof la.subarray&&0===la.subarray(1,1).byteLength}catch(ra){return!1}}function ja(la,ra){if((ha.Ae?2147483647:1073741823)<ra)throw new RangeError("Invalid typed array length");ha.Ae?(la=new Uint8Array(ra),la.__proto__=ha.prototype):(null===la&&(la=new ha(ra)),
la.length=ra);return la}function ha(la,ra,ua){if(!(ha.Ae||this instanceof ha))return new ha(la,ra,ua);if("number"===typeof la){if("string"===typeof ra)throw Error("If encoding is specified then the first argument must be a string");return r(this,la)}return ea(this,la,ra,ua)}function ea(la,ra,ua,pa){if("number"===typeof ra)throw new TypeError('"value" argument must not be a number');if("undefined"!==typeof ArrayBuffer&&ra instanceof ArrayBuffer){ra.byteLength;if(0>ua||ra.byteLength<ua)throw new RangeError("'offset' is out of bounds");
if(ra.byteLength<ua+(pa||0))throw new RangeError("'length' is out of bounds");ra=void 0===ua&&void 0===pa?new Uint8Array(ra):void 0===pa?new Uint8Array(ra,ua):new Uint8Array(ra,ua,pa);ha.Ae?(la=ra,la.__proto__=ha.prototype):la=x(la,ra);ra=la}else if("string"===typeof ra){pa=la;la=ua;if("string"!==typeof la||""===la)la="utf8";if(!ha.tR(la))throw new TypeError('"encoding" must be a valid string encoding');ua=b(ra,la)|0;pa=ja(pa,ua);ra=pa.write(ra,la);ra!==ua&&(pa=pa.slice(0,ra));ra=pa}else ra=f(la,
ra);return ra}function z(la){if("number"!==typeof la)throw new TypeError('"size" argument must be a number');if(0>la)throw new RangeError('"size" argument must not be negative');}function r(la,ra){z(ra);la=ja(la,0>ra?0:a(ra)|0);if(!ha.Ae)for(var ua=0;ua<ra;++ua)la[ua]=0;return la}function x(la,ra){var ua=0>ra.length?0:a(ra.length)|0;la=ja(la,ua);for(var pa=0;pa<ua;pa+=1)la[pa]=ra[pa]&255;return la}function f(la,ra){if(ha.isBuffer(ra)){var ua=a(ra.length)|0;la=ja(la,ua);if(0===la.length)return la;
ra.copy(la,0,0,ua);return la}if(ra){if("undefined"!==typeof ArrayBuffer&&ra.buffer instanceof ArrayBuffer||"length"in ra)return(ua="number"!==typeof ra.length)||(ua=ra.length,ua=ua!==ua),ua?ja(la,0):x(la,ra);if("Buffer"===ra.type&&ma(ra.data))return x(la,ra.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");}function a(la){if(la>=(ha.Ae?2147483647:1073741823))throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+
(ha.Ae?2147483647:1073741823).toString(16)+" bytes");return la|0}function b(la,ra){if(ha.isBuffer(la))return la.length;if("undefined"!==typeof ArrayBuffer&&"function"===typeof ArrayBuffer.isView&&(ArrayBuffer.isView(la)||la instanceof ArrayBuffer))return la.byteLength;"string"!==typeof la&&(la=""+la);var ua=la.length;if(0===ua)return 0;for(var pa=!1;;)switch(ra){case "ascii":case "latin1":case "binary":return ua;case "utf8":case "utf-8":case void 0:return da(la).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*
ua;case "hex":return ua>>>1;case "base64":return ia(la).length;default:if(pa)return da(la).length;ra=(""+ra).toLowerCase();pa=!0}}function e(la,ra,ua){var pa=!1;if(void 0===ra||0>ra)ra=0;if(ra>this.length)return"";if(void 0===ua||ua>this.length)ua=this.length;if(0>=ua)return"";ua>>>=0;ra>>>=0;if(ua<=ra)return"";for(la||(la="utf8");;)switch(la){case "hex":la=ra;ra=ua;ua=this.length;if(!la||0>la)la=0;if(!ra||0>ra||ra>ua)ra=ua;pa="";for(ua=la;ua<ra;++ua)la=pa,pa=this[ua],pa=16>pa?"0"+pa.toString(16):
pa.toString(16),pa=la+pa;return pa;case "utf8":case "utf-8":return aa(this,ra,ua);case "ascii":la="";for(ua=Math.min(this.length,ua);ra<ua;++ra)la+=String.fromCharCode(this[ra]&127);return la;case "latin1":case "binary":la="";for(ua=Math.min(this.length,ua);ra<ua;++ra)la+=String.fromCharCode(this[ra]);return la;case "base64":return 0===ra&&ua===this.length?na.FP(this):na.FP(this.slice(ra,ua));case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":ra=this.slice(ra,ua);ua="";for(la=0;la<ra.length;la+=
2)ua+=String.fromCharCode(ra[la]+256*ra[la+1]);return ua;default:if(pa)throw new TypeError("Unknown encoding: "+la);la=(la+"").toLowerCase();pa=!0}}function h(la,ra,ua,pa,xa){if(0===la.length)return-1;"string"===typeof ua?(pa=ua,ua=0):2147483647<ua?ua=2147483647:-2147483648>ua&&(ua=-2147483648);ua=+ua;isNaN(ua)&&(ua=xa?0:la.length-1);0>ua&&(ua=la.length+ua);if(ua>=la.length){if(xa)return-1;ua=la.length-1}else if(0>ua)if(xa)ua=0;else return-1;"string"===typeof ra&&(ra=ha.from(ra,pa));if(ha.isBuffer(ra))return 0===
ra.length?-1:n(la,ra,ua,pa,xa);if("number"===typeof ra)return ra&=255,ha.Ae&&"function"===typeof Uint8Array.prototype.indexOf?xa?Uint8Array.prototype.indexOf.call(la,ra,ua):Uint8Array.prototype.lastIndexOf.call(la,ra,ua):n(la,[ra],ua,pa,xa);throw new TypeError("val must be string, number or Buffer");}function n(la,ra,ua,pa,xa){function Ea(Oa,Ma){return 1===Ka?Oa[Ma]:Oa.Uv(Ma*Ka)}var Ka=1,Ja=la.length,Ca=ra.length;if(void 0!==pa&&(pa=String(pa).toLowerCase(),"ucs2"===pa||"ucs-2"===pa||"utf16le"===
pa||"utf-16le"===pa)){if(2>la.length||2>ra.length)return-1;Ka=2;Ja/=2;Ca/=2;ua/=2}if(xa)for(pa=-1;ua<Ja;ua++)if(Ea(la,ua)===Ea(ra,-1===pa?0:ua-pa)){if(-1===pa&&(pa=ua),ua-pa+1===Ca)return pa*Ka}else-1!==pa&&(ua-=ua-pa),pa=-1;else for(ua+Ca>Ja&&(ua=Ja-Ca);0<=ua;ua--){Ja=!0;for(pa=0;pa<Ca;pa++)if(Ea(la,ua+pa)!==Ea(ra,pa)){Ja=!1;break}if(Ja)return ua}return-1}function aa(la,ra,ua){ua=Math.min(la.length,ua);for(var pa=[];ra<ua;){var xa=la[ra],Ea=null,Ka=239<xa?4:223<xa?3:191<xa?2:1;if(ra+Ka<=ua)switch(Ka){case 1:128>
xa&&(Ea=xa);break;case 2:var Ja=la[ra+1];128===(Ja&192)&&(xa=(xa&31)<<6|Ja&63,127<xa&&(Ea=xa));break;case 3:Ja=la[ra+1];var Ca=la[ra+2];128===(Ja&192)&&128===(Ca&192)&&(xa=(xa&15)<<12|(Ja&63)<<6|Ca&63,2047<xa&&(55296>xa||57343<xa)&&(Ea=xa));break;case 4:Ja=la[ra+1];Ca=la[ra+2];var Oa=la[ra+3];128===(Ja&192)&&128===(Ca&192)&&128===(Oa&192)&&(xa=(xa&15)<<18|(Ja&63)<<12|(Ca&63)<<6|Oa&63,65535<xa&&1114112>xa&&(Ea=xa))}null===Ea?(Ea=65533,Ka=1):65535<Ea&&(Ea-=65536,pa.push(Ea>>>10&1023|55296),Ea=56320|
Ea&1023);pa.push(Ea);ra+=Ka}la=pa.length;if(la<=oa)pa=String.fromCharCode.apply(String,pa);else{ua="";for(ra=0;ra<la;)ua+=String.fromCharCode.apply(String,pa.slice(ra,ra+=oa));pa=ua}return pa}function y(la,ra,ua){if(0!==la%1||0>la)throw new RangeError("offset is not uint");if(la+ra>ua)throw new RangeError("Trying to access beyond buffer length");}function ba(la,ra,ua,pa,xa,Ea){if(!ha.isBuffer(la))throw new TypeError('"buffer" argument must be a Buffer instance');if(ra>xa||ra<Ea)throw new RangeError('"value" argument is out of bounds');
if(ua+pa>la.length)throw new RangeError("Index out of range");}function da(la,ra){ra=ra||Infinity;for(var ua,pa=la.length,xa=null,Ea=[],Ka=0;Ka<pa;++Ka){ua=la.charCodeAt(Ka);if(55295<ua&&57344>ua){if(!xa){if(56319<ua){-1<(ra-=3)&&Ea.push(239,191,189);continue}else if(Ka+1===pa){-1<(ra-=3)&&Ea.push(239,191,189);continue}xa=ua;continue}if(56320>ua){-1<(ra-=3)&&Ea.push(239,191,189);xa=ua;continue}ua=(xa-55296<<10|ua-56320)+65536}else xa&&-1<(ra-=3)&&Ea.push(239,191,189);xa=null;if(128>ua){if(0>--ra)break;
Ea.push(ua)}else if(2048>ua){if(0>(ra-=2))break;Ea.push(ua>>6|192,ua&63|128)}else if(65536>ua){if(0>(ra-=3))break;Ea.push(ua>>12|224,ua>>6&63|128,ua&63|128)}else if(1114112>ua){if(0>(ra-=4))break;Ea.push(ua>>18|240,ua>>12&63|128,ua>>6&63|128,ua&63|128)}else throw Error("Invalid code point");}return Ea}function fa(la){for(var ra=[],ua=0;ua<la.length;++ua)ra.push(la.charCodeAt(ua)&255);return ra}function ia(la){var ra=na,ua=ra.Ffa;la=(la.trim?la.trim():la.replace(/^\s+|\s+$/g,"")).replace(ta,"");if(2>
la.length)la="";else for(;0!==la.length%4;)la+="=";return ua.call(ra,la)}function ca(la,ra,ua,pa){for(var xa=0;xa<pa&&!(xa+ua>=ra.length||xa>=la.length);++xa)ra[xa+ua]=la[xa];return xa}var na=w(413);w(414);var ma=w(415);wa.Buffer=ha;wa.Sga=function(la){+la!=la&&(la=0);return ha.PN(+la)};wa.uX=50;ha.Ae=void 0!==qa.Ae?qa.Ae:ka();wa.kja=ha.Ae?2147483647:1073741823;ha.from=function(la,ra,ua){return ea(null,la,ra,ua)};ha.Ae&&(ha.prototype.__proto__=Uint8Array.prototype,ha.__proto__=Uint8Array,"undefined"!==
typeof Symbol&&Symbol.species&&ha[Symbol.species]===ha&&Object.defineProperty(ha,Symbol.species,{value:null,configurable:!0}));ha.PN=function(la){z(la);return ja(null,la)};ha.allocUnsafe=function(la){return r(null,la)};ha.isBuffer=function(la){return!(null==la||!la.QZ)};ha.compare=function(la,ra){if(!ha.isBuffer(la)||!ha.isBuffer(ra))throw new TypeError("Arguments must be Buffers");if(la===ra)return 0;for(var ua=la.length,pa=ra.length,xa=0,Ea=Math.min(ua,pa);xa<Ea;++xa)if(la[xa]!==ra[xa]){ua=la[xa];
pa=ra[xa];break}return ua<pa?-1:pa<ua?1:0};ha.tR=function(la){switch(String(la).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;default:return!1}};ha.concat=function(la,ra){if(!ma(la))throw new TypeError('"list" argument must be an Array of Buffers');if(0===la.length)return ha.PN(0);var ua;if(void 0===ra)for(ua=ra=0;ua<la.length;++ua)ra+=la[ua].length;ra=ha.allocUnsafe(ra);var pa=
0;for(ua=0;ua<la.length;++ua){var xa=la[ua];if(!ha.isBuffer(xa))throw new TypeError('"list" argument must be an Array of Buffers');xa.copy(ra,pa);pa+=xa.length}return ra};ha.byteLength=b;ha.prototype.QZ=!0;ha.prototype.toString=function(){var la=this.length|0;return 0===la?"":0===arguments.length?aa(this,0,la):e.apply(this,arguments)};ha.prototype.Lq=function(la){if(!ha.isBuffer(la))throw new TypeError("Argument must be a Buffer");return this===la?!0:0===ha.compare(this,la)};ha.prototype.inspect=
function(){var la="",ra=wa.uX;0<this.length&&(la=this.toString("hex",0,ra).match(/.{2}/g).join(" "),this.length>ra&&(la+=" ... "));return"<Buffer "+la+">"};ha.prototype.compare=function(la,ra,ua,pa,xa){if(!ha.isBuffer(la))throw new TypeError("Argument must be a Buffer");void 0===ra&&(ra=0);void 0===ua&&(ua=la?la.length:0);void 0===pa&&(pa=0);void 0===xa&&(xa=this.length);if(0>ra||ua>la.length||0>pa||xa>this.length)throw new RangeError("out of range index");if(pa>=xa&&ra>=ua)return 0;if(pa>=xa)return-1;
if(ra>=ua)return 1;ra>>>=0;ua>>>=0;pa>>>=0;xa>>>=0;if(this===la)return 0;var Ea=xa-pa,Ka=ua-ra,Ja=Math.min(Ea,Ka);pa=this.slice(pa,xa);la=la.slice(ra,ua);for(ra=0;ra<Ja;++ra)if(pa[ra]!==la[ra]){Ea=pa[ra];Ka=la[ra];break}return Ea<Ka?-1:Ka<Ea?1:0};ha.prototype.includes=function(la,ra,ua){return-1!==this.indexOf(la,ra,ua)};ha.prototype.indexOf=function(la,ra,ua){return h(this,la,ra,ua,!0)};ha.prototype.lastIndexOf=function(la,ra,ua){return h(this,la,ra,ua,!1)};ha.prototype.write=function(la,ra,ua,pa){if(void 0===
ra)pa="utf8",ua=this.length,ra=0;else if(void 0===ua&&"string"===typeof ra)pa=ra,ua=this.length,ra=0;else if(isFinite(ra))ra|=0,isFinite(ua)?(ua|=0,void 0===pa&&(pa="utf8")):(pa=ua,ua=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var xa=this.length-ra;if(void 0===ua||ua>xa)ua=xa;if(0<la.length&&(0>ua||0>ra)||ra>this.length)throw new RangeError("Attempt to write outside buffer bounds");pa||(pa="utf8");for(xa=!1;;)switch(pa){case "hex":ra=Number(ra)||
0;pa=this.length-ra;ua?(ua=Number(ua),ua>pa&&(ua=pa)):ua=pa;pa=la.length;if(0!==pa%2)throw new TypeError("Invalid hex string");ua>pa/2&&(ua=pa/2);for(pa=0;pa<ua;++pa){xa=parseInt(la.substr(2*pa,2),16);if(isNaN(xa))break;this[ra+pa]=xa}return pa;case "utf8":case "utf-8":return ca(da(la,this.length-ra),this,ra,ua);case "ascii":return ca(fa(la),this,ra,ua);case "latin1":case "binary":return ca(fa(la),this,ra,ua);case "base64":return ca(ia(la),this,ra,ua);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":pa=
la;xa=this.length-ra;for(var Ea=[],Ka=0;Ka<pa.length&&!(0>(xa-=2));++Ka){var Ja=pa.charCodeAt(Ka);la=Ja>>8;Ja%=256;Ea.push(Ja);Ea.push(la)}return ca(Ea,this,ra,ua);default:if(xa)throw new TypeError("Unknown encoding: "+pa);pa=(""+pa).toLowerCase();xa=!0}};ha.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this.vha||this,0)}};var oa=4096;ha.prototype.slice=function(la,ra){var ua=this.length;la=~~la;ra=void 0===ra?ua:~~ra;0>la?(la+=ua,0>la&&(la=0)):la>ua&&(la=ua);0>
ra?(ra+=ua,0>ra&&(ra=0)):ra>ua&&(ra=ua);ra<la&&(ra=la);if(ha.Ae)ra=this.subarray(la,ra),ra.__proto__=ha.prototype;else{ua=ra-la;ra=new ha(ua,void 0);for(var pa=0;pa<ua;++pa)ra[pa]=this[pa+la]}return ra};ha.prototype.XI=function(la){y(la,1,this.length);return this[la]};ha.prototype.Uv=function(la){y(la,2,this.length);return this[la]<<8|this[la+1]};ha.prototype.Bga=function(la,ra){la=+la;ra|=0;ba(this,la,ra,1,255,0);ha.Ae||(la=Math.floor(la));this[ra]=la&255;return ra+1};ha.prototype.Aga=function(la,
ra){la=+la;ra|=0;ba(this,la,ra,4,4294967295,0);if(ha.Ae)this[ra]=la>>>24,this[ra+1]=la>>>16,this[ra+2]=la>>>8,this[ra+3]=la&255;else{var ua=ra;0>la&&(la=4294967295+la+1);for(var pa=0,xa=Math.min(this.length-ua,4);pa<xa;++pa)this[ua+pa]=la>>>8*(3-pa)&255}return ra+4};ha.prototype.copy=function(la,ra,ua,pa){ua||(ua=0);pa||0===pa||(pa=this.length);ra>=la.length&&(ra=la.length);ra||(ra=0);0<pa&&pa<ua&&(pa=ua);if(pa===ua||0===la.length||0===this.length)return 0;if(0>ra)throw new RangeError("targetStart out of bounds");
if(0>ua||ua>=this.length)throw new RangeError("sourceStart out of bounds");if(0>pa)throw new RangeError("sourceEnd out of bounds");pa>this.length&&(pa=this.length);la.length-ra<pa-ua&&(pa=la.length-ra+ua);var xa=pa-ua;if(this===la&&ua<ra&&ra<pa)for(pa=xa-1;0<=pa;--pa)la[pa+ra]=this[pa+ua];else if(1E3>xa||!ha.Ae)for(pa=0;pa<xa;++pa)la[pa+ra]=this[pa+ua];else Uint8Array.prototype.set.call(la,this.subarray(ua,ua+xa),ra);return xa};ha.prototype.fill=function(la,ra,ua,pa){if("string"===typeof la){"string"===
typeof ra?(pa=ra,ra=0,ua=this.length):"string"===typeof ua&&(pa=ua,ua=this.length);if(1===la.length){var xa=la.charCodeAt(0);256>xa&&(la=xa)}if(void 0!==pa&&"string"!==typeof pa)throw new TypeError("encoding must be a string");if("string"===typeof pa&&!ha.tR(pa))throw new TypeError("Unknown encoding: "+pa);}else"number"===typeof la&&(la&=255);if(0>ra||this.length<ra||this.length<ua)throw new RangeError("Out of range index");if(ua<=ra)return this;ra>>>=0;ua=void 0===ua?this.length:ua>>>0;la||(la=0);
if("number"===typeof la)for(pa=ra;pa<ua;++pa)this[pa]=la;else for(la=ha.isBuffer(la)?la:da((new ha(la,pa)).toString()),xa=la.length,pa=0;pa<ua-ra;++pa)this[pa+ra]=la[pa%xa];return this};var ta=/[^+\/0-9A-Za-z-_]/g}).call(this,w(170))},413:function(Da,wa){function w(ha){var ea=ha.length;if(0<ea%4)throw Error("Invalid string. Length must be a multiple of 4");ha=ha.indexOf("=");-1===ha&&(ha=ea);return[ha,ha===ea?0:4-ha%4]}wa.byteLength=function(ha){ha=w(ha);var ea=ha[1];return 3*(ha[0]+ea)/4-ea};wa.Ffa=
function(ha){var ea=w(ha);var z=ea[0];ea=ea[1];var r=new ja(3*(z+ea)/4-ea),x=0,f=0<ea?z-4:z,a;for(a=0;a<f;a+=4)z=ka[ha.charCodeAt(a)]<<18|ka[ha.charCodeAt(a+1)]<<12|ka[ha.charCodeAt(a+2)]<<6|ka[ha.charCodeAt(a+3)],r[x++]=z>>16&255,r[x++]=z>>8&255,r[x++]=z&255;2===ea&&(z=ka[ha.charCodeAt(a)]<<2|ka[ha.charCodeAt(a+1)]>>4,r[x++]=z&255);1===ea&&(z=ka[ha.charCodeAt(a)]<<10|ka[ha.charCodeAt(a+1)]<<4|ka[ha.charCodeAt(a+2)]>>2,r[x++]=z>>8&255,r[x++]=z&255);return r};wa.FP=function(ha){for(var ea=ha.length,
z=ea%3,r=[],x=0,f=ea-z;x<f;x+=16383){for(var a=r,b=a.push,e,h=ha,n=x+16383>f?f:x+16383,aa=[],y=x;y<n;y+=3)e=(h[y]<<16&16711680)+(h[y+1]<<8&65280)+(h[y+2]&255),aa.push(qa[e>>18&63]+qa[e>>12&63]+qa[e>>6&63]+qa[e&63]);e=aa.join("");b.call(a,e)}1===z?(ha=ha[ea-1],r.push(qa[ha>>2]+qa[ha<<4&63]+"==")):2===z&&(ha=(ha[ea-2]<<8)+ha[ea-1],r.push(qa[ha>>10]+qa[ha>>4&63]+qa[ha<<2&63]+"="));return r.join("")};var qa=[],ka=[],ja="undefined"!==typeof Uint8Array?Uint8Array:Array;for(Da=0;64>Da;++Da)qa[Da]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Da],
ka["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(Da)]=Da;ka[45]=62;ka[95]=63},414:function(Da,wa){wa.read=function(w,qa,ka,ja,ha){var ea=8*ha-ja-1;var z=(1<<ea)-1,r=z>>1,x=-7;ha=ka?ha-1:0;var f=ka?-1:1,a=w[qa+ha];ha+=f;ka=a&(1<<-x)-1;a>>=-x;for(x+=ea;0<x;ka=256*ka+w[qa+ha],ha+=f,x-=8);ea=ka&(1<<-x)-1;ka>>=-x;for(x+=ja;0<x;ea=256*ea+w[qa+ha],ha+=f,x-=8);if(0===ka)ka=1-r;else{if(ka===z)return ea?NaN:Infinity*(a?-1:1);ea+=Math.pow(2,ja);ka-=r}return(a?-1:1)*ea*Math.pow(2,
ka-ja)};wa.write=function(w,qa,ka,ja,ha,ea){var z,r=8*ea-ha-1,x=(1<<r)-1,f=x>>1,a=23===ha?Math.pow(2,-24)-Math.pow(2,-77):0;ea=ja?0:ea-1;var b=ja?1:-1,e=0>qa||0===qa&&0>1/qa?1:0;qa=Math.abs(qa);isNaN(qa)||Infinity===qa?(qa=isNaN(qa)?1:0,ja=x):(ja=Math.floor(Math.log(qa)/Math.LN2),1>qa*(z=Math.pow(2,-ja))&&(ja--,z*=2),qa=1<=ja+f?qa+a/z:qa+a*Math.pow(2,1-f),2<=qa*z&&(ja++,z/=2),ja+f>=x?(qa=0,ja=x):1<=ja+f?(qa=(qa*z-1)*Math.pow(2,ha),ja+=f):(qa=qa*Math.pow(2,f-1)*Math.pow(2,ha),ja=0));for(;8<=ha;w[ka+
ea]=qa&255,ea+=b,qa/=256,ha-=8);ja=ja<<ha|qa;for(r+=ha;0<r;w[ka+ea]=ja&255,ea+=b,ja/=256,r-=8);w[ka+ea-b]|=128*e}},415:function(Da){var wa={}.toString;Da.exports=Array.isArray||function(w){return"[object Array]"==wa.call(w)}}}]);}).call(this || window)
