/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{395:function(Da,wa,w){function qa(y,ba,da){ba.endsWith("/")||(ba+="/");da=da||{};var fa=da.disableWebsockets||!1;this.rV=da.singleServerMode||!1;null!=da.customQueryParameters&&Object(h.b)("wvsQueryParameters",da.customQueryParameters);ba.endsWith("blackbox/")||(ba+="blackbox/");this.Zm=da.uploadData||null;this.Mw=da.uriData||null;this.oO=da.cacheKey||null;this.xS=da.officeLocale||null;this.$t=Object(f.a)(ba,null,fa);this.Se=
ba;this.DF=y;this.kf=null;this.sj=ja();this.Zl=ja();this.qz=!1;this.Zf=this.Jd=this.ce=this.Re=null;this.pf=[];this.aA=[];this.cache={};this.timeStamp=0;this.Kf=[];this.$g=[];this.bG=null;this.uF=!1;this.zJ=this.id=null;this.ZH=this.WQ=ha;this.jC=0;this.dH=!1;this.sS=1;this.Vh={};this.mq=0;this.Qr=ka();this.Bp(!0)}function ka(){var y={kr:{},tb:[],pop:function(){var ba=y.tb.pop();y.kr[ba.key]=void 0;return ba},push:function(ba,da){da={key:ba,data:da};y.tb.push(da);y.kr[ba]=da.data},contains:function(ba){return!!y.kr[ba]},
get:function(ba){return y.kr[ba]},set:function(ba,da){y.kr[ba]=da;y.tb.forEach(function(fa,ia){fa.key==ba&&(y.tb[ia]=fa)})},remove:function(ba){y.kr[ba]=void 0;y.tb.forEach(function(da,fa){da.key==ba&&y.tb.splice(fa,1)})},length:function(){return y.tb.length}};return y}function ja(){var y={promise:null,resolve:null,reject:null,state:0,result:null,request:null,vr:function(){return 1===(y.state&1)},r9:function(){return 2===(y.state&2)},Sh:function(){return!y.r9()&&!y.vr()},U8:function(){return 4===
(y.state&4)},NU:function(){y.state|=4}};y.promise=new Promise(function(ba,da){y.resolve=function(){if(0===y.state||4===y.state)y.state=1,y.result=arguments[0],ba.apply(null,arguments)};y.reject=function(){if(0===y.state||4===y.state)y.state=2,da.apply(null,arguments)}});return y}function ha(){return!1}function ea(y,ba,da){if(!(ba in aa))return!0;ba=aa[ba];for(var fa=0;fa<ba.length;fa++){var ia=y;var ca=ba[fa];var na=da;if(ca.name in ia){var ma="",oa=!1;ia=ia[ca.name];switch(ca.type){case "s":ma="String";
oa=Object(z.isString)(ia);break;case "a":ma="Array";oa=Object(z.isArray)(ia);break;case "n":ma="Number";oa=Object(z.isNumber)(ia)&&Object(z.isFinite)(ia);break;case "o":ma="Object",oa=Object(z.isObject)(ia)&&!Object(z.isArray)(ia)}oa||na.reject('Expected response field "'+ca.name+'" to have type '+ma);ca=oa}else na.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}w.r(wa);var z=w(0);w.n(z);var r=w(2);Da=w(49);var x=w(29),f=w(412),a=w(88),b=w(352),e=w(108),h=w(42),n=w(155),
aa={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};qa.prototype=Object(z.extend)(qa.prototype,
{B2:function(){var y=this;return new Promise(function(ba,da){var fa=new XMLHttpRequest;fa.open("GET",y.Se+"ck");fa.withCredentials=y.xk();fa.onreadystatechange=function(){fa.readyState===XMLHttpRequest.DONE&&(200===fa.status?ba():da())};fa.send()})},Tda:function(y,ba){this.WQ=y||ha;this.ZH=ba||ha},DO:function(){var y=this;this.Zl=ja();this.sj=ja();return this.$t.RF().then(function(){y.qz=!1;y.id=null;y.uF=!1;return y.B2()})},kJ:function(){this.WQ();this.tH();this.Re&&(this.Re.Sh()?this.zg(this.Re.request):
this.Re.vr()&&this.ZH(this.Re.result.url,"pdf")&&(this.Re=null,this.lU()));this.Zf&&this.Zf.Sh()&&this.zg(this.Zf.request);this.ce&&this.ce.Sh()?this.zg(this.ce.request):this.Jd&&this.Jd.Sh()&&this.LQ(this.Jd.request);var y;for(y=0;y<this.Kf.length;y++)this.Kf[y]&&this.Kf[y]&&(this.Kf[y].Sh()?this.zg(this.Kf[y].request):this.Kf[y].vr()&&this.ZH(this.Kf[y].result.url,"image")&&(this.Kf[y]=null,this.gC(Object(z.uniqueId)(),y)));for(y=0;y<this.$g.length;y++)this.$g[y]&&this.$g[y]&&this.$g[y].Sh()&&!this.$g[y].U8()&&
this.zg(this.$g[y].request);for(y=0;y<this.pf.length;y++)this.pf[y]&&this.pf[y].Sh()&&this.zg(this.pf[y].request)},tH:function(y){var ba=this;this.qz||(this.timeStamp=Date.now(),this.$t.eK(function(da){ba.H$(da)},function(){return null},function(){return null},!0).then(function(){clearInterval(ba.ZB);ba.ZB=null},function(da){ba.qz=!1;if(!ba.ZB){var fa=0;ba.uF=!0;ba.zJ=0;ba.ZB=setInterval(function(){2>fa++?ba.kJ():(clearInterval(ba.ZB),y&&y.reject(e.a),Object(r.f)("WebViewerServer connection failed:"+
da))},5E3)}}),this.qz=!0)},jga:function(){var y=this,ba=createPromiseCapability();if(this.Zm){var da=new FormData;da.append("file",this.Zm.fileHandle,this.Zm.fileHandle.name);var fa=this.Zm.loadCallback;var ia="upload";var ca=this.Zm.extension}else if(this.Mw){da={uri:this.Mw.uri,Yja:this.Mw.shareId};da=Object.keys(da).map(function(ta){return ta+"="+(da[ta]?encodeURIComponent(da[ta]):"")}).join("&");var na="application/x-www-form-urlencoded; charset=UTF-8";fa=this.Mw.loadCallback;ia="url";ca=this.Mw.extension}else return Promise.resolve();
var ma=new XMLHttpRequest,oa=Object(x.j)(y.Se,"AuxUpload");oa=Object(n.a)(oa)+"&type="+ia+"&ext="+ca;ma.open("POST",oa);ma.withCredentials=this.xk();na&&ma.setRequestHeader("Content-Type",na);ma.addEventListener("load",function(){if(ma.readyState===ma.DONE&&200===ma.status){var ta=JSON.parse(ma.response);y.DF=ta.uri;fa(ta);ba.resolve(ta)}});ma.addEventListener("error",function(){ba.reject(ma.statusText+" "+JSON.stringify(ma))});this.Zm&&null!=this.Zm.onProgress&&(ma.upload.onprogress=function(ta){y.Zm.onProgress(ta)});
ma.send(da);return ba.promise},wca:function(y){this.password=y||null;this.sj.vr()||(this.sj=ja(),this.zg({t:"pages"}));return this.sj.promise},$v:function(y){this.bG=y||null;this.sj.vr()||(this.tH(this.sj),this.zg({t:"pages"}));return this.sj.promise},Zt:function(y){y=Object.assign(y,{uri:encodeURIComponent(this.DF)});this.bG&&(y.ext=this.bG);this.kf&&(y.c=this.kf);this.password&&(y.pswd=this.password);this.oO&&(y.cacheKey=this.oO);this.xS&&(y.locale=this.xS);return y},ada:function(){0<this.Qr.length()&&
10>=this.mq&&this.bda(this.Qr.pop().data)},W0:function(y){return 0<this.Qr.length()&&this.Qr.contains(y)?(this.Qr.remove(y),!0):!1},zg:function(y){y=this.Zt(y);this.$t.send(y)},CU:function(y,ba){10<this.mq?this.Qr.push(y,ba):(this.mq++,y=this.Zt(ba),this.$t.send(y))},bda:function(y){this.mq++;y=this.Zt(y);this.$t.send(y)},jk:function(y){return y},H$:function(y){var ba=this,da=y.data,fa=y.err,ia=y.t;switch(ia){case "upload":fa?ba.kga.reject(fa):ba.kga.resolve("Success");break;case "pages":fa?ba.sj.reject(fa):
ea(da,ia,ba.sj)&&ba.sj.resolve(da);break;case "config":if(fa)ba.Zl.reject(fa);else if(ea(da,ia,ba.Zl)){da.id&&(ba.id=da.id);if(da.auth){var ca=Object(h.a)("wvsQueryParameters");ca.auth=da.auth;Object(h.b)("wvsQueryParameters",ca)}da.serverVersion&&(ba.xW=da.serverVersion,Object(r.g)("[WebViewer Server] server version: "+ba.xW));da.serverID?(ba.jC=da.serverID===ba.zJ&&ba.dH?ba.jC+1:0,ba.zJ=da.serverID):ba.jC=0;ba.dH=!1;ba.Zl.resolve(da)}break;case "health":fa?ba.Zl.reject(fa):ea(da,ia,ba.Zl)&&(da=
da.unhealthy,ba.rV&&da?Object(r.i)("Server failed health check. Single server mode ignoring check."):!ba.pia&&da&&1>=ba.jC&&(ba.dH=!0,ba.DO().then(function(){ba.kJ()},function(){ba.kJ()})));break;case "pdf":da.url=Object(n.a)(ba.Se+"../"+encodeURI(da.url));fa?ba.Re.reject(fa):ea(da,ia,ba.Re)&&ba.Re.resolve(da);break;case "ApString2Xod":da.url=Object(n.a)(ba.Se+"../data/"+encodeURI(da.url));fa?ba.Vh[da.rID].reject(fa):ea(da,ia,ba.Vh[da.rID])&&ba.Vh[da.rID].resolve(da);break;case "docmod":da.url=Object(n.a)(ba.Se+
"../"+encodeURI(da.url));fa?ba.Vh[da.rID].reject(fa):ea(da,ia,ba.Re)&&ba.Vh[da.rID].resolve(da);break;case "xod":if(fa)this.ce&&this.ce.Sh()&&this.ce.reject(fa),this.Jd&&this.Jd.Sh()&&this.Jd.reject(fa);else if(da.notFound)da.noCreate||this.ce&&this.ce.Sh()&&this.ce.resolve(da),this.Jd&&this.Jd.Sh()&&this.Jd.resolve(da);else{da.url&&(da.url=Object(n.a)(ba.Se+"../"+encodeURI(da.url)));if(!this.Jd||this.Jd.vr())this.Jd=ja(),this.Jd.request={t:"xod",noCreate:!0};this.ce||(this.ce=ja(),this.ce.request=
{t:"xod"});this.Jd.resolve(da);this.ce.resolve(da)}break;case "annots":if(fa)ba.Zf.reject(fa);else if(ea(da,ia,ba.Zf)){ba.Zf.NU();var na=new XMLHttpRequest;ca=ba.Se+"../"+encodeURI(da.url);var ma=da.hasAppearance?Object(n.a)(ca+".xodapp"):null;na.open("GET",Object(n.a)(ca));na.responseType="text";na.withCredentials=this.xk();na.addEventListener("load",function(){na.readyState===na.DONE&&200===na.status&&ba.Zf.resolve({BK:na.response,Vy:ma})});na.addEventListener("error",function(){ba.Zf.reject(na.statusText+
" "+JSON.stringify(na))});na.send()}break;case "image":ba.mq--;var oa=this.Kf[da.p];fa?oa.promise.reject(fa):ea(da,ia,oa)&&(oa.result=da,oa.result.url=Object(n.a)(ba.Se+"../"+encodeURI(oa.result.url)),oa.resolve(oa.result));break;case "tiles":ba.mq--;oa=da.rID;ca=this.pf[oa];this.pf[oa]=null;this.aA.push(oa);if(fa)ca.reject(fa);else if(ea(da,ia,ca)){for(fa=0;fa<da.tiles.length;fa++)da.tiles[fa]=Object(n.a)(ba.Se+"../"+encodeURI(da.tiles[fa]));ca.resolve(da)}break;case "text":oa=this.$g[da.p];if(fa)oa.reject(fa);
else if(ea(da,ia,oa)){oa.NU();var ta=new XMLHttpRequest;da=Object(n.a)(ba.Se+"../"+encodeURI(da.url));ta.open("GET",da);ta.withCredentials=this.xk();ta.addEventListener("load",function(){ta.readyState===ta.DONE&&200===ta.status&&(oa.result=JSON.parse(ta.response),oa.resolve(oa.result))});ta.addEventListener("error",function(la){oa.reject(ta.statusText+" "+JSON.stringify(la))});ta.send()}break;case "progress":"loading"===da.t&&ba.trigger(a.a.Events.DOCUMENT_LOADING_PROGRESS,[da.bytes,da.total])}this.ada();
!ia&&y.echo&&y&&"apstring2xod"==y.echo.t&&(y=y.echo.reqID)&&(2<=parseInt(ba.xW)?ba.Vh[y].reject("Message unhandled by server"):ba.Vh[y].reject())},VP:function(){this.tH(this.Zl);return this.Zl.promise},Y5:function(y){for(var ba=this,da=new XMLHttpRequest,fa=Object(n.a)(this.Se+"aul")+"&id="+this.id,ia=new FormData,ca={},na=0;na<y.body.length;na++){var ma=y.body[na];ca[ma.id]=ma.LE.w+";"+ma.LE.h;ia.append(ma.id,ma.LE.dataString)}y={t:"apstring2xod",reqID:this.sS++,parts:ca};var oa=this.Zt(y);ia.append("msg",
JSON.stringify(oa));ba.Vh[oa.reqID]=ja();da.open("POST",fa);da.withCredentials=ba.xk;fa=new Promise(function(ta,la){da.onreadystatechange=function(){4===da.readyState&&(200===da.status?ta():la("An error occurred while sending down appearance strings to the server"))}});da.send(ia);return fa.then(function(){return ba.Vh[oa.reqID].promise})},X5:function(){this.Zf||(this.Zf=ja(),this.Zf.request={t:"annots"},this.zg(this.Zf.request));return this.Zf.promise},gC:function(y,ba){this.Kf[ba]||(this.Kf[ba]=
ja(),this.Kf[ba].request={t:"image",p:ba},this.CU(y,this.Kf[ba].request));return this.Kf[ba].promise},xca:function(y){this.$g[y]||(this.$g[y]=ja(),this.$g[y].request={t:"text",p:y},this.zg(this.$g[y].request));return this.$g[y].promise},yca:function(y,ba,da,fa,ia){var ca=this.pf.length;this.aA.length&&(ca=this.aA.pop());this.pf[ca]=ja();this.pf[ca].request={t:"tiles",p:ba,z:da,r:fa,size:ia,rID:ca};this.CU(y,this.pf[ca].request);return this.pf[ca].promise},lU:function(){this.Re||(this.Re=ja(),this.Re.request=
{t:"pdf"},this.uF?this.Re.resolve({url:this.DF}):this.zg(this.Re.request));return this.Re.promise},mQ:function(y){var ba=this,da=new XMLHttpRequest,fa=Object(n.a)(this.Se+"aul")+"&id="+this.id,ia=new FormData,ca={};y.annots&&(ca.annots="xfdf");y.watermark&&(ca.watermark="png");y.redactions&&(ca.redactions="redact");ca={t:"docmod",reqID:this.sS++,parts:ca};y.print&&(ca.print=!0);var na=this.Zt(ca);ia.append("msg",JSON.stringify(na));return Promise.all([y.annots,y.watermark,y.redactions].map(function(ma){return Promise.resolve(ma)})).then(function(ma){var oa=
ma[0],ta=ma[1],la=ma[2];oa&&ia.append("annots",oa);ta&&ia.append("watermark",ma.watermark);la&&ia.append("redactions",la);ba.Vh[na.reqID]=ja();da.open("POST",fa);da.withCredentials=ba.xk;ma=new Promise(function(ra,ua){da.onreadystatechange=function(){4===da.readyState&&(200===da.status?ra():ua("An error occurred while sending down annotation data to the server"))}});da.send(ia);return ma.then(function(){return ba.Vh[na.reqID].promise})})},LQ:function(){this.Jd||(this.Jd=ja(),this.Jd.request={t:"xod",
noCreate:!0},this.zg(this.Jd.request));return this.Jd.promise},zca:function(){this.ce||(this.ce=ja(),this.ce.request={t:"xod"},this.zg(this.ce.request));return this.ce.promise},Mm:function(){return!0},request:function(){},ET:function(){},abort:function(){for(var y=0;y<this.pf.length;y++)this.pf[y]&&(this.pf[y].resolve(null),this.pf[y]=null,this.aA.push(y));this.close()},sC:function(y){this.kf=this.kf||{};this.kf.headers=y},Jia:function(){return this.kf?Object(z.omit)(this.kf.headers,["Cookie","cookie"]):
null},Bp:function(y){this.kf=this.kf||{};this.kf.internal=this.kf.internal||{};this.kf.internal.withCredentials=y},xk:function(){return this.kf&&this.kf.internal?this.kf.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(Da.a)(qa);Object(b.a)(qa);Object(b.b)(qa);wa["default"]=qa},412:function(Da,wa,w){function qa(z,r,x){function f(b,e){function h(ta){aa().then(function(la){ca&&!na?setTimeout(function(){h(ta)},1):la.send(JSON.stringify(ta))})}function n(ta,la,ra,
ua){var pa=window.createPromiseCapability(),xa=!1,Ea=pa;da=ta;fa=la;ia=ra;ba=null;ua&&(ta=Object(ha.a)("wvsQueryParameters"),ta.bcid=Object(ja.k)(8),Object(ha.b)("wvsQueryParameters",ta));try{ta=ma?oa+"/"+ma:oa+"/ws";ta=Object(ea.a)(ta);var Ka=new WebSocket(ta);Ka.onopen=function(){pa.resolve();xa=!0;pa=null;ca=!1;y.resolve(Ka);fa&&fa()};Ka.onerror=function(Ja){ca=na=!0;pa&&pa.reject(Ja);ba&&ba.reject()};Ka.onclose=function(){y=window.createPromiseCapability();ca=!0;ba||(ba=window.createPromiseCapability());
ba.resolve();ia&&ia();da&&xa&&da({t:"health",data:{unhealthy:!0,isDead:!0}})};Ka.onmessage=function(Ja){Ja&&Ja.data&&(Ja=JSON.parse(Ja.data),Ja.hb?h({hb:!0}):Ja.end?close():da(Ja))}}catch(Ja){pa.reject(Ja),pa=null}return Ea.promise}function aa(){ca&&da&&n(da);return y.promise}var y=window.createPromiseCapability(),ba=null,da,fa,ia=null,ca=!1,na=!1,ma=e,oa=function(ta){var la=ta.indexOf("://"),ra="ws://";0>la?la=0:(5===la&&(ra="wss://"),la+=3);var ua=ta.lastIndexOf("/");0>ua&&(ua=ta.length);return ra+
ta.slice(la,ua)}(b);return{send:h,eK:n,RF:function(){return ba?ba.promise:aa().then(function(ta){ba=window.createPromiseCapability();da=null;ta.close();return ba.promise})}}}function a(b){var e=b.lastIndexOf("/");0>e&&(e=b.length);return b.slice(0,e)}return window.WebSocket&&!x?f(z,r):function(b,e){function h(ta){(ia?ia.promise:Promise.resolve(fa)).then(function(la){var ra=new XMLHttpRequest,ua=da?ba+"/"+da+"pf":ba+"/pf";ua=Object(ea.a)(ua)+"&id="+la;la=new FormData;la.append("data",JSON.stringify(ta));
ra.open("POST",ua);ra.withCredentials=!0;ra.send(la)})}function n(){fa=0;ia||(ia=window.createPromiseCapability())}function aa(){y=new XMLHttpRequest;var ta=ba+"/pf";ta+=0!==fa?"?id="+fa+"&uc="+oa:"?uc="+oa;oa++;y.open("GET",ta,!0);y.withCredentials=!0;y.setRequestHeader("Cache-Control","no-cache");y.setRequestHeader("X-Requested-With","XMLHttpRequest");var la=y,ra=!1;y.onreadystatechange=function(){a:if(3<=la.readyState&&!ra){try{var ua=la.responseText.length}catch(Ea){Object(ka.g)("caught exception");
break a}if(0<ua)try{var pa=la.responseText.split("\n");for(pa[pa.length-1]&&pa.pop();0<pa.length&&3>pa[pa.length-1].length;)"]"===pa.pop()&&n();0<pa.length&&3>pa[0].length&&pa.shift();for(ua=0;ua<pa.length;++ua)pa[ua].endsWith(",")&&(pa[ua]=pa[ua].substr(0,pa[ua].length-1));0===fa&&0<pa.length&&(fa=JSON.parse(pa.shift()).id,ua=ia,ia=null,ua.resolve(fa));var xa;for(ua=0;ua<pa.length;++ua)(xa=JSON.parse(pa[ua]))&&xa.end?close():xa&&xa.hb&&xa.id===fa?h({hb:!0}):ma(xa)}catch(Ea){}ca||(ra=!0,aa())}};y.send()}
var y,ba=a(b),da=e,fa=0,ia=window.createPromiseCapability(),ca=!1,na=null,ma=null,oa=0;return{send:h,eK:function(ta,la,ra){ma=ta;na=ra;ca=!1;n();aa();la&&la();return Promise.resolve()},RF:function(){n();ma=null;ca=!0;na&&na();y.abort();return Promise.resolve()}}}(z,r)}w.d(wa,"a",function(){return qa});var ka=w(2),ja=w(29),ha=w(42),ea=w(155)}}]);}).call(this || window)
